### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by seabassh** [hiro942/FedFSL-IDS-Exp#1]
你好，能否给出一下数据集，我在Kaggle上下载了CIC-IDS-2017的数据集来运行您的代码，但是还是存在一些数据的问题。能否上传一下你使用的数据集呢？感谢

**Comment by hiro942** [comment]
我用的是从 https://www.unb.ca/cic/datasets/ids-2017.html 官方下载的数据集，使用 CSV 格式的，应该和 Kaggle 下的是一样的吧？另外，我这边还在不断调试和更新代码，可能会存在一些问题。但是目前来说数据是没问题的了。你可以描述一下你遇到的数据问题是什么，看看我能不能帮你解决。

**Comment by seabassh** [comment]
好的，谢谢，我明天试试

**Comment by seabassh** [comment]
1.你好，你使用的是GeneratedLabelledFlows的数据集文件吗？
2.这些代码正常的运行逻辑应该是把data_folder修改成自己的文件夹，然后就可以直接运行main.py了吧？还是有其他地方需要调整修改的？

**Comment by hiro942** [comment]
用处理好的MachineLearningCVE里面的

**Comment by seabassh** [comment]
你好，我尝试了一下MachineLearningCVE里面的全部文件放在同一个文件夹下进行运行，发现会报错。然后调整，使用2个或者3个文件来作为数据集，发现会出现不同种类的报错。请问具体是使用哪几个数据集呢？还是说MachineLearningCVE里的csv文件需要手动处理呢？麻烦了，感谢

**Comment by seabassh** [comment]
你好，我看到你应该是读取了2个csv文件，因为 if index == 2:
            break  。想问一下你使用的是哪两个csv文件呢？

**Comment by hiro942** [comment]
我更新了代码你可以拉一下，我跑了一遍，数据是没问题的，用的是MachineLearningCVE全部的csv。如果还有报错的话，贴一下相关信息我好帮你看看。

**Comment by seabassh** [comment]
Traceback (most recent call last):
  File "/Users/Downloads/FedFSL-IDS-Exp-main-2/main.py", line 197, in <module>
    fed_train(meta=meta, model=g_model, clients=clients, val_loader=base_val_loader, is_pretrain=True)
  File "/Users/Downloads/FedFSL-IDS-Exp-main-2/main.py", line 43, in fed_train
    local_model = copy.deepcopy(model)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 306, in _reconstruct
    value = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.7/site-packages/torch/_tensor.py", line 103, in __deepcopy__
    "Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
 用了新的代码跑了一遍，感觉现在数据集没有问题了，不知道为什么现在出现这个问题，网上找了一下也不知道怎么解决的。
我在代码里就是把main里面的df = read_files()里面的参数改成了自己的CVE文件夹路径，然后直接运行main的。不知道哪里出现的问题。感谢你的解答！

**Comment by hiro942** [comment]
若像您说的只改了文件读取路径其他没改的话，我确实没遇到这种问题，查了一些可能的解决方案，看看对你有没有帮助。
https://stackoverflow.com/questions/56590886/how-to-solve-the-run-time-error-only-tensors-created-explicitly-by-the-user-gr

https://blog.csdn.net/XCCCCZ/article/details/128794986?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-128794986-blog-129259194.235%5Ev38%5Epc_relevant_anti_vip&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-128794986-blog-129259194.235%5Ev38%5Epc_relevant_anti_vip&utm_relevant_index=4

https://blog.csdn.net/weixin_37112382/article/details/129259194

如果还是不行，试试打断点看看具体哪一行报错了，或者试试 python3.8。

**Comment by seabassh** [comment]
你好，能否给一个requirements.txt呢？感觉应该是环境问题。我试试按照你的环境来操作一下

**Comment by hiro942** [comment]
我目前出差，手头没有环境，这个感觉是deepcopy的问题你升级下python版本到3.8试一下。

**Comment by seabassh** [comment]
嗯好的，我跑了一下，改成3.8能正常用了，谢谢
